# Generated by Django 6.0.4 on 2026-04-17 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingrecord',
            name='parkingspot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parking_records', to='parkings.parkingspot', verbose_name='Vaga'),
        ),
    ]
